name: release

on:
  push:
    tags:
      - '*'

  workflow_dispatch:
    inputs:
      tag:
        required: true

jobs:
  release:
    name: release
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: 7z x -p"${{ secrets.PASSWORD }}" windivert-sniffer.7z
      - run: cargo build --release -p windivert-sniffer
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/release/windivert-sniffer.dll"
          tag: ${{ github.event.inputs.tag }}
